# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
default: &default
  host: 127.0.0.1
  username: root
  password: root
  database: testmine
  adapter: mysql2
  pool: 5
  timeout: 5000

development:
  <<: *default

test:
  <<: *default

integration:
  <<: *default

production:
  <<: *default
  host: <%=ENV['DATABASE_HOST'] || 'localhost' %>
  username: <%=ENV['DATABASE_USERNAME'] || 'root' %>
  database: <%=ENV['DATABASE_NAME'] || 'testmine' %>
  password: <%=ENV['DATABASE_PASSWORD']%>
  adapter: mysql2
